info:
  app:
    name: "@project.artifactId@"
    description: "@project.name@"
    version: "@project.version@"
#server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-alias: dataflow
#    key-store: "/your/path/to/dataflow.keystore"
#    key-store-type: jks
#    key-store-password: dataflow
#    key-password: dataflow

# Basic Authentication:

#security:
#  basic:
#    enabled: true
#    realm: Spring Cloud Data Flow
#  user:
#    name: your-username
#    password: your-password
#    role: VIEW, CREATE, MANAGE

# Oauth 2 support:

#security:
#  oauth2:
#    client:
#      client-id: myclient
#      client-secret: mysecret
#      access-token-uri: http://127.0.0.1:9999/oauth/token
#      user-authorization-uri: http://127.0.0.1:9999/oauth/authorize
#    resource:
#      user-info-uri: http://127.0.0.1:9999/me

# If you prefer to use Eureka to locate the Config Server, you can do that by setting
# spring.cloud.config.discovery.enabled=true (default "false"). The net result of that is
# that client apps all need a bootstrap.yml (or an environment variable) with the Eureka
# server address, e.g. in eureka.client.serviceUrl.defaultZone
#
#---
spring:
  application:
    name: "@project.artifactId@"
  cloud:
    config:
      enabled: false
      discovery:
           enabled: true
# tag::configuration-eureka[]
eureka:  #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management.security.enabled: false  #<2>
# end::configuration-eureka[]

# tag::configuration-ui-hystrix[]
spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
# end::configuration-ui-hystrix[]

# tag::configuration-ui-turbine[]
spring.boot.admin.turbine:
  clusters: default
  location: turbine  #<1>
# end::configuration-ui-turbine[]
